project_id = "jhxjvpbwkdzjufjyqanq"

[functions.generate-briefing-content]
verify_jwt = false

[functions.morning-market-analysis]
verify_jwt = false

[functions.post-market-analysis]
verify_jwt = false

[functions.kg-prediction-enhancer]
verify_jwt = false

[functions.kg-daily-update]
verify_jwt = false