project_id = "jhxjvpbwkdzjufjyqanq"

[functions.morning-market-analysis]
verify_jwt = false

[functions.post-market-analysis]
verify_jwt = false

[functions.kg-prediction-enhancer]
verify_jwt = false

[functions.kg-daily-update]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.ai-knowledge-query]
verify_jwt = true

[functions.trader-signals]
verify_jwt = false

[functions.trader-account]
verify_jwt = false

[functions.trader-positions]
verify_jwt = false

[functions.trader-execute]
verify_jwt = false

[functions.analyze-markets]
verify_jwt = false

[functions.execute-trade]
verify_jwt = false

[functions.trading-engine]
verify_jwt = false

[functions.execute-trades]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.update-positions]
verify_jwt = false

[functions.sync-beehiiv-subscriber]
verify_jwt = true

[functions.generate-newsletter-content]
verify_jwt = true

[functions.push-newsletter-to-beehiiv]
verify_jwt = true

[functions.push-newsletter-to-kit]
verify_jwt = true

[functions.sync-kit-subscriber]
verify_jwt = true

[functions.diagnostics]
verify_jwt = true

[functions.stock-analysis]
verify_jwt = true

[functions.cognee-query]
verify_jwt = true

[functions.forensic-document-analysis]
verify_jwt = true

[functions.scrape-kroll-documents]
verify_jwt = true

[functions.process-kroll-email]
verify_jwt = false

[functions.forensic-ai-assistant]
verify_jwt = true

[functions.reprocess-documents]
verify_jwt = true

[functions.get-user-amps]
verify_jwt = true

[functions.add-user-amp]
verify_jwt = true

[functions.toggle-amp-active]
verify_jwt = true

[functions.allocate-capital]
verify_jwt = true

[functions.update-amp-settings]
verify_jwt = true

[functions.get-amp-performance]
verify_jwt = true

[functions.get-amp-events]
verify_jwt = true

[functions.admin-user-lookup]
verify_jwt = true

[functions.market-news]
verify_jwt = true

[functions.generate-amp-covers]
verify_jwt = true
