project_id = "jhxjvpbwkdzjufjyqanq"

[functions.generate-briefing-content]
verify_jwt = false

[functions.morning-market-analysis]
verify_jwt = false

[functions.post-market-analysis]
verify_jwt = false

[functions.kg-prediction-enhancer]
verify_jwt = false

[functions.kg-daily-update]
verify_jwt = false

[functions.process-document]
verify_jwt = true

[functions.ai-knowledge-query]
verify_jwt = true

[functions.trader-signals]
verify_jwt = false

[functions.trader-account]
verify_jwt = false

[functions.trader-positions]
verify_jwt = false

[functions.trader-execute]
verify_jwt = false

[functions.analyze-markets]
verify_jwt = false

[functions.execute-trade]
verify_jwt = false

[functions.trading-engine]
verify_jwt = false

[functions.execute-trades]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.update-positions]
verify_jwt = false

[functions.sync-beehiiv-subscriber]
verify_jwt = true