-- Create the trading schema to completely separate trading data from educational content
CREATE SCHEMA IF NOT EXISTS trading;

-- Create trading.signals table
CREATE TABLE trading.signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('BUY', 'SELL', 'HOLD')),
    confidence DECIMAL(5,2) NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
    current_price DECIMAL(12,4) NOT NULL CHECK (current_price > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create trading.positions table
CREATE TABLE trading.positions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity != 0),
    avg_cost DECIMAL(12,4) NOT NULL CHECK (avg_cost > 0),
    current_price DECIMAL(12,4) NOT NULL CHECK (current_price > 0),
    pnl DECIMAL(12,2) NOT NULL,
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security on trading tables
ALTER TABLE trading.signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE trading.positions ENABLE ROW LEVEL SECURITY;

-- Create restrictive policies that block all access for now
CREATE POLICY "Block all access to signals" 
ON trading.signals 
FOR ALL 
USING (false) 
WITH CHECK (false);

CREATE POLICY "Block all access to positions" 
ON trading.positions 
FOR ALL 
USING (false) 
WITH CHECK (false);

-- Add indexes for performance
CREATE INDEX idx_trading_signals_symbol ON trading.signals(symbol);
CREATE INDEX idx_trading_signals_created_at ON trading.signals(created_at DESC);
CREATE INDEX idx_trading_positions_symbol ON trading.positions(symbol);
CREATE INDEX idx_trading_positions_opened_at ON trading.positions(opened_at DESC);

-- Add comments for documentation
COMMENT ON SCHEMA trading IS 'Isolated schema for trading platform data - completely separate from educational content';
COMMENT ON TABLE trading.signals IS 'Trading signals generated by algorithms - blocked until regulatory approval';
COMMENT ON TABLE trading.positions IS 'Trading positions and P&L tracking - blocked until regulatory approval';