-- Manually insert sample algorithm performance data for today
INSERT INTO algorithm_performance (
    date,
    algorithm_version,
    total_predictions,
    directional_accuracy,
    high_accuracy_avg,
    low_accuracy_avg,
    close_accuracy_avg,
    confidence_calibration,
    average_confidence,
    high_within_half_percent,
    low_within_half_percent,
    close_within_half_percent,
    high_time_accuracy_minutes,
    low_time_accuracy_minutes,
    trending_market_accuracy,
    choppy_market_accuracy,
    high_volatility_accuracy,
    low_volatility_accuracy,
    confidence_accuracy_correlation,
    best_performing_signal,
    worst_performing_signal,
    signal_performance,
    pattern_performance,
    created_at
) VALUES (
    '2025-09-25',
    'v1.0',
    20,
    78.5,
    82.3,
    79.1,
    75.8,
    73.2,
    74.6,
    15,
    16,
    14,
    45.2,
    38.7,
    81.2,
    72.4,
    68.9,
    84.3,
    0.68,
    'technical_analysis',
    'news_sentiment',
    '{"technical_analysis": 0.82, "options_flow": 0.79, "microstructure": 0.76, "news_sentiment": 0.64, "macro_data": 0.71}'::jsonb,
    '{"breakout_patterns": 0.85, "support_resistance": 0.78, "trend_continuation": 0.73, "reversal_signals": 0.69}'::jsonb,
    NOW()
)
ON CONFLICT (date) DO UPDATE SET
    total_predictions = EXCLUDED.total_predictions,
    directional_accuracy = EXCLUDED.directional_accuracy,
    high_accuracy_avg = EXCLUDED.high_accuracy_avg,
    low_accuracy_avg = EXCLUDED.low_accuracy_avg,
    close_accuracy_avg = EXCLUDED.close_accuracy_avg,
    confidence_calibration = EXCLUDED.confidence_calibration,
    average_confidence = EXCLUDED.average_confidence,
    high_within_half_percent = EXCLUDED.high_within_half_percent,
    low_within_half_percent = EXCLUDED.low_within_half_percent,
    close_within_half_percent = EXCLUDED.close_within_half_percent,
    high_time_accuracy_minutes = EXCLUDED.high_time_accuracy_minutes,
    low_time_accuracy_minutes = EXCLUDED.low_time_accuracy_minutes,
    trending_market_accuracy = EXCLUDED.trending_market_accuracy,
    choppy_market_accuracy = EXCLUDED.choppy_market_accuracy,
    high_volatility_accuracy = EXCLUDED.high_volatility_accuracy,
    low_volatility_accuracy = EXCLUDED.low_volatility_accuracy,
    confidence_accuracy_correlation = EXCLUDED.confidence_accuracy_correlation,
    best_performing_signal = EXCLUDED.best_performing_signal,
    worst_performing_signal = EXCLUDED.worst_performing_signal,
    signal_performance = EXCLUDED.signal_performance,
    pattern_performance = EXCLUDED.pattern_performance,
    created_at = NOW();